baseurl: '/JavaTraining'

defaults:
  -  
    scope:
      path: ""
      type: "pages"
    values:
      section: ""
      layout: "default"
  -
    scope:
      path: "introductions"
      type: "pages"
    values: 
      section: "introductions"