baseurl: '/JavaTraining'

defaults:
  -  
    scope:
      path: ""
      type: "pages"
    values:
      section: ""
            layout: "default"
            description: "AndroidTraining - Training course repository for android app development"
            og_type: "article"
    -
        scope:
            path: "introductions"
            type: "pages"
        values: 
            section: "introductions"