baseurl: '/JavaTraining'
markdown: "redcarpet"

defaults:
  -  
    scope:
      path: ""
      type: "pages"
    values:
      section: ""
      layout: "default"
  -
    scope:
      path: "introductions"
      type: "pages"
    values: 
      section: "introductions"
  -
    scope:
      path: "fundamentals"
      type: "pages"
    values: 
      section: "fundamentals"
  -
    scope:
      path: "structure"
      type: "pages"
    values: 
      section: "structure"